export default [
  {
    segmento: "P",
    segPosition: [13,13],
    layout: [
      { name: "Banco Código do Banco na Compensação", positions: [0, 2] },
      { name: "Lote", positions: [3, 6] },
      { name: "Tipo de Registro", positions: [7, 7] },
      { name: "Nº do Registro", positions: [8, 12] },
      { name: "idSegmento", positions: [13, 13] },
      { name: "CNAB", positions: [14, 14] },
      { name: "Código de Movimento", positions: [15, 16] },
      { name: "Código Agência Mantenedora da Conta", positions: [17, 21] },
      { name: "Dígito Verificador da Agência", positions: [22, 22] },
      { name: "Número da Conta Corrente", positions: [23, 34] },
      { name: "Dígito Verificador da Conta", positions: [35, 35] },
      { name: "Dígito Verificador da Ag/Conta", positions: [36, 36] },
      { name: "Identificação do Título no Banco", positions: [37, 56] },
      { name: "Código da Carteira", positions: [57, 57] },
      { name: "Forma de Cadastr. do Título no Banco", positions: [58, 58] },
      { name: "Tipo de Documento", positions: [59, 59] },
      { name: "Identificação da Emissão do Boleto de Pagamento", positions: [60, 60] },
      { name: "Identificação da Distribuição", positions: [61, 61] },
      { name: "Número do Documento de Cobrança", positions: [62, 76] },
      { name: "Data de Vencimento do Título", positions: [77, 84] },
      { name: "Valor Nominal do Título", positions: [85, 99] },
      { name: "Agência Encarregada da Cobrança", positions: [100, 104] },
      { name: "Dígito Verificador da Agência", positions: [105, 105] },
      { name: "Espécie do Título", positions: [106, 107] },
      { name: "Identific. de Título Aceito/Não Aceito", positions: [108, 108] },
      { name: "Data da Emissão do Título", positions: [109, 116] },
      { name: "Código do Juros de Mora", positions: [117, 117] },
      { name: "Data do Juros de Mora", positions: [118, 125] },
      { name: "Juros de Mora por Dia/Taxa", positions: [126, 140] },
      { name: "Código do Desconto 1", positions: [141, 141] },
      { name: "Data do Desconto 1", positions: [142, 149] },
      { name: "Valor/Percentual a ser Concedido", positions: [150, 164] },
      { name: "Valor do IOF a ser Recolhido", positions: [165, 179] },
      { name: "Valor do Abatimento", positions: [180, 194] },
      { name: "Identificação do Título na Empresa", positions: [195, 219] },
      { name: "Código para Protesto", positions: [220, 220] },
      { name: "Número de Dias para Protesto", positions: [221, 222] },
      { name: "Código para Baixa/Devolução", positions: [223, 223] },
      { name: "Número de Dias para Baixa/Devolução", positions: [224, 226] },
      { name: "Código da Moeda", positions: [227, 228] },
      { name: "Nº do Contrato da Operação de Créd.", positions: [229, 238] },
      { name: "Uso livre banco/empresa", positions: [239, 239] }
    ]
  },
  {
    segmento: "Q",
    segPosition: [13,13],
    layout: [
      { name: "Banco Código do Banco na Compensação", positions: [0, 2] },
      { name: "Lote", positions: [3, 6] },
      { name: "Tipo de Registro", positions: [7, 7], default: "3" },
      { name: "Nº do Registro", positions: [8, 12] },
      { name: "idSegmento", positions: [13, 13], default: "Q" },
      { name: "CNAB", positions: [14, 14] },
      { name: "Código de Movimento", positions: [15, 16] },
      { name: "Tipo de Inscrição", positions: [17, 17] },
      { name: "Número de Inscrição", positions: [18, 32] },
      { name: "Empresa", positions: [33, 72] },
      { name: "Endereço", positions: [73, 112] },
      { name: "Bairro", positions: [113, 127] },
      { name: "CEP", positions: [128, 132] },
      { name: "Sufixo do CEP", positions: [133, 135] },
      { name: "Cidade", positions: [136, 150] },
      { name: "Unidade da Federação", positions: [151, 152] },
      { name: "Tipo de Inscrição do Sacador/Avalista", positions: [153, 153] },
      { name: "Número de Inscrição do Sacador/Avalista", positions: [154, 168] },
      { name: "Nome do Sacador/Avalista", positions: [169, 208] },
      { name: "Código Bco. Corresp. na Compensação", positions: [209, 211] },
      { name: "Nosso Nº no Banco Correspondente", positions: [212, 231] },
      { name: "CNAB", positions: [232, 239] }
    ]
  },
  {
    segmento: "R",
    segPosition: [13,13],
    layout: [
      { name: "Banco Código do Banco na Compensação", positions: [0, 2] },
      { name: "Lote", positions: [3, 6] },
      { name: "Tipo de Registro", positions: [7, 7], default: "3" },
      { name: "Nº do Registro", positions: [8, 12] },
      { name: "idSegmento", positions: [13, 13], default: "R" },
      { name: "CNAB", positions: [14, 14] },
      { name: "Código de Movimento", positions: [15, 16] },
      { name: "Código do Desconto 2", positions: [17, 17] },
      { name: "Data do Desconto 2", positions: [18, 25] },
      { name: "Valor/Percentual a ser Concedido", positions: [26, 40] },
      { name: "Código do Desconto 3", positions: [41, 41] },
      { name: "Data do Desconto 3", positions: [42, 49] },
      { name: "Valor/Percentual a Ser Concedido", positions: [50, 64] },
      { name: "Código da Multa", positions: [65, 65] },
      { name: "Data da Multa", positions: [66, 73] },
      { name: "Valor/Percentual a Ser Aplicado", positions: [74, 88] },
      { name: "Informação ao Pagador", positions: [89, 98] },
      { name: "Mensagem 3", positions: [99, 138] },
      { name: "Mensagem 4", positions: [139, 178] },
      { name: "CNAB", positions: [179, 199] },
      { name: "Código Ocor. do Pagador", positions: [200, 206] },
      { name: "Cód. do Banco na Conta do Débito", positions: [207, 209] },
      { name: "Código da Agência do Débito", positions: [210, 214] },
      { name: "Dígito Verificador da Agência", positions: [215, 215] },
      { name: "Conta Corrente para Débito", positions: [216, 227] },
      { name: "Dígito Verificador da Conta", positions: [228, 228] },
      { name: "Dígito Verificador Ag/Conta", positions: [229, 229] },
      { name: "Aviso para Débito Automático", positions: [230, 230] },
      { name: "CNAB", positions: [231, 239] }
    ]
  }
];
